version: 0.2

phases:
  install:
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
      - cd $CODEBUILD_SRC_DIR/$APP_DIR;yarn install
  build:
    commands:
      - $CODEBUILD_SRC_DIR/$APP_DIR/node_modules/.bin/webpack --mode=production
      # Copy deployspec as build artifact for 
      - cp $CODEBUILD_SRC_DIR/deployspec.yml $CODEBUILD_SRC_DIR/$APP_DIR/
artifacts:
  files:
    - '**/*'
  base-directory: $APP_DIR
cache:
  paths:
    - '/root/.yarn-cache/**/*'