version: 0.2

phases:
  install:
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
      - cd $CODEBUILD_SRC_DIR/$APP_DIR;yarn install
  build:
    commands:
      - $CODEBUILD_SRC_DIR/$APP_DIR/node_modules/.bin/webpack --mode=production
      # Copy required files
      - mkdir -p $CODEBUILD_SRC_DIR/build/dist
      - cp $CODEBUILD_SRC_DIR/$APP_DIR/index.html $CODEBUILD_SRC_DIR/build/
      - cp $CODEBUILD_SRC_DIR/$APP_DIR/main.css $CODEBUILD_SRC_DIR/build/
      - cp -a $CODEBUILD_SRC_DIR/$APP_DIR/dist/. $CODEBUILD_SRC_DIR/build/dist/      
      # Copy deployspec as build artifact for deploy stage
      - cp $CODEBUILD_SRC_DIR/deployspec.yml $CODEBUILD_SRC_DIR/build/
      - yarn cache dir
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - '/usr/local/share/.cache/yarn/v1/**/*'